apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgC95gLFCBXY6J9C38mTIDjYgprlsGNBuQMKSejZkBOEnA3JIJg0hHeIwtbgxlfHdLRGnhFGQgXGxRIlCzQd72zrqXwpbQm31GvaTl1kso9YrVGFHlcBmYNNNgDC0l57Bn3ThDf7j+6ONfNzJldh50iqWpXeiqBOKBXAxJFhcDBgW6NZZOSxEgOCcSK6HmY2wvApN5soSHR/sgeI8Il2sBz+OrQKoZ291/n6XJqYSqA63sf53BUmOinaMIx0CzWlUmwerWGf/D8r2KPmvdj47wtyza0ULJ/jSF9vek6lbxwaEy+XLqcgDFc1Q/g1xF0+e0pjj/X9z9Qa6TZdUGzO0oGc/aPz4WVPBUH36lrGfmDijvk+wMYQMO2OCRV8GDfcQ180KIAMtL//NOksVwCOnCxKkFYAVM4fs15UzwWigcvL4lfkHgWH/pnesPb+fYUIn5NqJHF7S7RnIQTKGtv5bt1pGV0HhHsavObLDHbuPbk8fsvMGQ6Uc+Lqf5QuJF04c+HfVuE2K/LorcX9GZxkb5vuvbffhokKFd1r2/DUSjhzLy9abEbdcXdejPpj0UizuLIT4kqWSjIQBk4tWqudWUdlVHLHp6Ps4puPcPCZcSssG/E09wDHMFPpSHOcBh25CW1zAa7r0C1MReGIuWfzT4kXlxPkEgNP/EkSXPxkBCcgi6IS1BmkAIold0lHra0aIGQyoAT1xMiD9g==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

