apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAJKxAQLAG9ghlrJYfvvHf0TuTmZtRysx7c/jnY6LxZpND/fCY/18PRVr+T6gGqyAxhmdbqzu0yrqvMeZluW6iK0PPchkNzyfPS7ROHAzNeBOJwoILMaxrZ25Dlo5HF4b0gn7L6Kr54jsFKkdTJ8SQ4I8yFfqm2G7QNUKZp9xR3NvAhkjmYcvQZLOYbwLB+BR9JgMaALOWtlQ4EO63i2LIxqb3m4O+juzj6MPcB1kv3Q7sqpGx40pyaysv9MeWui3zegYxt3I0XucNLmhEjlJvGgmyZ14IeiKvRGhQ9uEVnm7xRomm11Z1xNzbG0Rer2wchq4QmLWpmzowyBj0F/ac7hrxlYfFx8k+3K1g228rUYGA7VdNfOPS2g8G3CH7LqAD6NUnzmhVB6z5gEK5Qm/GWUWLZmeS2eeNKiobLcid8K0yOb13YJ9oZkvK8mOl9xcMHOH8veDdhOrisontDCdr6/pMaK01p9Bkf5I8mpf01S9n7UX8feLfS50RwiaAzTTqQAb3mc/6PFE8MGaIGFCYQsR7v6ObAxz6gNRULaLq95qKQiuWOklsUKOlijpYYT4DaPnfZUkPezqC6j/dbeh9rNB9UnZEkRzfmaUFcpEZ7xhYKXgG/xmtf6mwPf0EsbO8q8+mn1zOET7Mkyk4ROK75mWQ7WubmNV9qNn5cLIL1Bk5qG3BIEmrJZOV66pTt4B6l87yg5sqD5g==
    DB_USER: AgCyj27m8BgpIjS3f9wJAzhysYG4yHLOH4ljkvjVTl7+UPZDL8B9ZNBt7aRlPhWgtp4Hxa3W5wJc0y2zW5gBiES0YNB24xoI8nI8PEvnzJbpaUbW8RbSugjBpeyGLDrZ43VtEJkEYmrd3ZnxQgv4xH8HaDF84YDndMtfWZHBb+KnB6RSZYbxoK6amPdBXuPg0CJXjUcdnaUcqclt1BN3o7Spu7b8SwEOcLPERdUMr9jF6vH/k1Tcb/bbP8Xj7V9ulA7jyzdbP5gezX55w1HQIuX+Wguv064kGBFrzqsv32Pc6OCgyg2ZUk43FGOKXFNwdxvv8Rc7p3XsdfqNH8YY9ZeG82jVz4xG6rG6cNiqHRvAGGTIEMaPZ/cUIVovCyyLpLXdJzrTo6ioSZ+7WoxSZc6wddoQGFzYvOCeT6sP56cmPpSnOJvEoaZYZix6sT/MgaFe8Z6s/KnrlKBBgLay7dYSd0PpjuU8sYusV7tAHM4f61gUBNiyRXLkezNTAwaMAU0mHKy18KCeSJq8yfq0+J/GQ2G0KSPp70MxTyc0xTI/y0kGZ5A6HS9MBxsnWGfC2y4vhOtUPZp2Q13lwhhC6gGMfo6unCj6+33BCHh/CR19hBHqkAviKUjtTm6y1uOq++41hX50PLwdQwAcaSdYdw8AHEUY6RN7fGkd6kQrUu0l6s3/q7Xu2gdY2wZepEgn85z7DxZVaz0jwQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

