# secret-creator-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-binding
  namespace: b2bi-prod
subjects:
- kind: ServiceAccount
  name: default
  namespace: b2bi-prod
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io
