service-account:
  name: b2bi
  create: false
  sccs: ["anyuid"]

ibm-sfg-prod:
  global:
    image:
      repository: cp.icr.io/cp/ibm-sfg/sfg
      tag: "6.1.0.0"
      pullPolicy: IfNotPresent
      pullSecret: ibm-entitlement-key
  serviceAccount:
    create: false
    name: b2bi
  appResourcesPVC:
    enabled: true
    name: resources
    storageClassName: managed-nfs-storage
    accessMode: ReadWriteMany
    size: 100Mi
  appLogsPVC:
    name: logs
    storageClassName: managed-nfs-storage
    accessMode: ReadWriteMany
    size: 500Mi
  appDocumentsPVC:
    enabled: true
    name: documents
    storageClassName: managed-nfs-storage
    accessMode: ReadWriteMany
    size: 500Mi
  security:
    supplementalGroups: [65534]
    fsGroup: 1010
    runAsUser: 1010
  dataSetup:
    enabled: false
    upgrade: false
  env:
    tz: "UTC"
    license: "accept"
    upgradeCompatibilityVerified: false
  logs:
    enableAppLogOnConsole: false

  setupCfg:
    basePort: 50000
    licenseAcceptEnableSfg: true
    systemPassphraseSecret: b2b-system-passphrase-secret
    enableFipsMode: false
    nistComplianceMode: "off"
    dbVendor: db2
    dbHost: 172.21.186.229
    dbPort: 50000
    dbData: B2BIDB
    dbDrivers: db2jcc4.jar
    dbCreateSchema: false
    dbSecret: b2b-db-secret
    adminEmailAddress: freitasb@br.ibm.com
    smtpHost: localhost
    jmsVendor: IBMMQ
    jmsConnectionFactory: com.ibm.mq.jms.MQQueueConnectionFactory
    jmsConnectionFactoryInstantiator:
    jmsQueueName: DEV.QUEUE.1
    jmsHost: 172.21.132.39
    jmsPort: 1414
    jmsConnectionNameList: 172.21.132.39(1414)
    jmsEnableSsl: false
    jmsChannel: DEV.APP.SVRCONN
    jmsSecret: b2b-jms-secret
    SANDBOX_LAUNCH_CLA2_SERVER: true

  asi:
    replicaCount: 1
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 60
    frontendService:
      type: ClusterIP
      ports:
        http:
          name: http
          port: 35000
          targetPort: http
          nodePort: 30000
          protocol: TCP
        https:
          name: https
          port: 35001
          targetPort: https
          nodePort: 30001
          protocol: TCP
        soa:
          name: soa
          port: 35002
          targetPort: soa
          nodePort: 30002
          protocol: TCP
        soassl:
          name: soassl
          port: 35003
          targetPort: soassl
          nodePort: 30003
          protocol: TCP
      extraPorts: []
    backendService:
      type: ClusterIP
      ports:
        - name: adapter-1
          port: 30201
          targetPort: 30201
          nodePort: 30201
          protocol: TCP
      portRanges:
        - name: adapters
          portRange: 30301-30305
          targetPortRange: 30301-30305
          nodePortRange: 30301-30305
          protocol: TCP
    ingress:
      internal:
        host: asi-b2bi-prod.itzroks-664003h6xc-6kgie8-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
        tls:
          enabled: true
          secretName: ""
        extraPaths: []

  ac:
    replicaCount: 1
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 60
    frontendService:
      type: ClusterIP
      ports:
        http:
          name: http
          port: 35004
          targetPort: http
          nodePort: 30004
          protocol: TCP
      extraPorts: []
    backendService:
      type: ClusterIP
      ports:
        - name: adapter-1
          port: 30401
          targetPort: 30401
          nodePort: 30401
          protocol: TCP
      portRanges: []
    ingress:
      internal:
        host: ac-b2bi-prod.itzroks-664003h6xc-6kgie8-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
        tls:
          enabled: true
          secretName: ""
        extraPaths: []

  api:
    replicaCount: 1
    frontendService:
      type: ClusterIP
      ports:
        http:
          name: http
          port: 35005
          targetPort: http
          nodePort: 30005
          protocol: TCP
        https:
          name: https
          port: 35006
          targetPort: https
          nodePort: 30006
          protocol: TCP
      extraPorts: []
    ingress:
      internal:
        host: api-b2bi-prod.itzroks-664003h6xc-6kgie8-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
        tls:
          enabled: true
          secretName: ""

  dashboard:
    enabled: true

  test:
    image:
      repository: 'ibmcom'
      name: 'opencontent-common-utils'
      tag: '1.1.4'
      pullPolicy: 'IfNotPresent'

  purge:
    enabled: false
    image:
      repository: cp.icr.io/cp/ibm-sfg/sfg-purge
      tag: "6.1.0.0"
      pullPolicy: IfNotPresent
      pullSecret: ibm-entitlement-key
    schedule: "*/30 * * * *"
    startingDeadlineSeconds:
    activeDeadlineSeconds: 3600
    concurrencyPolicy: Forbid
    suspend: false
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
